### ISSUE TITLE
Problems with .venv

### ISSUE THREAD

**Issue by EduardEdiJerkovic** [fbosnic/ratingsapp#6]
I have tried to create a virtual env as instructed and have a problem with it not finding the python version on my local computer. The error is:
```
pip3 install -r requirements.txt
    ERROR: Could not find a version that satisfies the requirement python>=3.8 (from versions: none)
    ERROR: No matching distribution found for python>=3.8
```

If I check the local installation on my computer with `py -0` I get the following:
```
Installed Pythons found by py Launcher for Windows
 -3.9-64 *
 -3.8-64
 -3.6-64
 -3.6-32
 ```
 
 Not sure what I'm missing to run this code?

**Comment by fbosnic** [comment]
It seems pip has problems installing python from requirements file. I think correct python version should already be installed before requirements are fetched. If that is the case, removing ```python>=3.8``` line will sort the issue.

Created separate requirements files for conda and pip, the issue should not happen in the future
